[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.mypy]
exclude = ["pyarn/parsetab.py"]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["ply", "pytest"]
ignore_missing_imports = true
